language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: vIqLIj2PIEW/DcVguHhdjmV3aspytQ+JAG3I+TZwro97VMgySBDmKku1/cnRXDPKkgIOFg5zEcv3x52Cn9ZNdtuJ/6HDuFAcBHtbbov7jc2grweKoU39G/EJAYk7xuRpcXO2h51A8PhYhqJNmUrQlUZic4NFenKJxu333rWhGy4O2KZgsccWRjZTg4xbCMAWwplM7Ps3j1WZ+nSgbuNZiRE7/Att9BTElSx1D0LP+YdAHDhGY5k0AbKvuv7ZL6FNNBw1r6tmwHHidVIvAbk3ullNQays+R/E2Pw3SRdtKCvxaC3oGmtbJ7ItDTuu0l8OCdNPB+xpXLmhDqOuMY4XAOhj6uyyp/kdRJ/WFLk3WHxoG2bmowziaINyoiJdWwBMg6/gUIWQD1JkPWGZlh+/lAwcXMaqgrEWIB1v94+4MxT/LBHq6Sz99ekTeZj1/qHbsDGcRIsUQtIKtbjEfO/xba4J1PKRy9xA2rFSaB5o6e3GDKzndYZ9hiUQVgb5NdPRXKY4+y/+JOn+2NF1lTMUhqeGPYgM3BHMXslBfHHlSuOrKUWJ9y92v3ZXwMooolqs9kykz6mDCPVa8WwNNb7Wek28ATewROVyUZTTdxAwkTXeN66mBOsS65Eb8lFtT4ANgjtXbjjbnc86muzdwCIvVDUz+TwCID2qoUa1RmdldrA=
  app: ouracademy
  skip_cleanup: true