language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: Rso+7yyvt6eZ5sbc/LIRbqJfugebHYVsonDuCwr6I1H477u//XQ+PpsTTHr9t7d5Iigu7RcR0m8MeCbZReC8OfTX2JeptWJntSJu86Z2ua2nsKNV9Z5eAAsqWp7QLgIYanGRNdtm/YE2BYriQOh9JS5Lj3W0It0QPzQXF1OZFFTBxR6C7ro8dVW0ZY2Des9TpOFU9y+q0NttAmheoBc6W6sI0GHMjC7MsShsYECFT062L7m7CuHkF7bvdz3gH4yM56Wrr0ZSah8vxxI5e+cVx7a6drRb10asT3jKjVgZ8GWcdCHJKSIluxvY4wCCO+mqQom2PDtg+lsluPCdFIHD8+F5CQMw1FH7kY2Iq8drCRmvJnJ0vm0+7hmPjOaqVUHBjVv9xAS3OF73vIIHhHxljM0jrk8M1b/MghgC2m8VGr50b0nWfRLO3tEzL8iHXEYQ/Ma12ILXzIF8g04GVOc9xgH1PURGWbBTZgicGZ896thJsiVpSn4+ZNVIYwzJOEVB+govqqgjH80QjRLuSpczYUX6Yn+H6uX040U7zZMYcDMCojV2a5SirGusKccy8hpCFj3m80gyvy0c64zbdMLS/ivtap2SQYsJ/isIPAp4scUfYx2j3M/qa6eoeChjBa5FBhcEY2w564v5c//4kYVnvvvodKbMyNdA+4wyOUEfglc=
  app: ouracademy
  on:
    repo: ouracademy/ouracademy.github.io
