language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: LguUS5TQ+DVN7l/GJ5nmGZxhoFY0y/PzoaAAcfD3jCOoUlKpUfYZYFlw01lv6EdBB2jfKaBsupI/heimSCNOXEqV5jzT/9Vr88U6mBLeHtJtq7rmDw1KA/sokcvZpedCX5HzzQU/G5Bsb+AltquA1oHhgQuaHkpJYznA7d8DIByyakBtjXaWI++qVtEioWwOXxl1pCK5uHUVYUR2vpHFlIe0nHl7VnlgZ7JnTVteAsebCcOCbol9H4uvkAN3XcXauD3NNq1MGz5jxrPz3USKgDSVzCs6tLrOXMzvglxjTWgluxVjO7L5o+g538dhq52Nl2w8GXA5w52ybIhY71aJ5y0uxOOiK5QkGNV9KexZlKfb4PqcMNXz8k9AbrzhsFIUOSbmQWlDQg4GFlbTvP13hgkodbUf2KvtPoP2WxKoo2tQsAyU3JpGao/eg/3CxBm7fyLpmangLb+2jiBlrVz9hcfnyrRxBWtkNaXpvxWjM0yEbXb6VNCSjnS0ZyAo5o+FDqG3uchibrn+2AppqLPSifU7xRAHyIKpF4qpSKCvLiRDnQkPi5JupaRGQP+bNnlFm9TS3XMrdMvKqTigS/gTKKvf9Jyq/tJQV3YrQC3Z4zK/3U8/dR3KgB7rX80gsAzd1GQs0OthxjHrNyMMVN8ZQSv5WYeVaiH58HlzeA/eEQE=
