language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: E+1I3tHM9ZDP61+K1m3AGRSBPoWlXDkzN+20XMltUbluTlQ3cUno/JOh5WMdScuAC2MFGuG4iLKRT5DwkomtdHrQWQwQ4i8FUehu7yfCN6S2wrfZ5a1CdDaEJkjVg051iKKUtUKEf1WyC4Vki1+BVv8hi4iuC+ecY1hR9UkJAJHj/tp2k7Kb7TKscopVuJ+M6BChgO2inA4E31FEldKVn/p2muipps7sdUrm+LbkOJ68AUfmMarDf2hrc3G+rw3UXdOqQcDiFwNUCJI7PyN2vy3isDNbCgIoVZBUtlsOhoOOIuhBJNXK559/NryW5DqgpukVJ6dtzXKOCNZaeM/KZvLrQfmABNJ5N03yi+gioOxWC7/EZfEpiZ467Ze845nnCTaDtvk1IJyLDkYS3h4KvX1Q/gy7vVLmUfzpleCcSCIln1wSEYx1AooX2c309s5DpcYLIPB+z9OXKl6LgYB3ETVhegmeXAyAhRGIZsL0K0tioyol6BpLFXSD01NwxhruSf+0Qqh7VOk1sfQDVS4L3uD8K9BnJaWpjAXV5UkjshqwrGUeGOBt9lsUcpebwFN4e/xM2aTpvqLGmb31L8QA8ldl19vGAF07FsDR6cSceEiPpvBzo+8vtWFxdaVOUfZhohj0UT8GQQ0indNayGKFBoNI3hJMFQTEL5lYIOV2+B8=
