language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: iTCNwWopBEjoEwx8SW2J6KbMjVRAC/R31D+v63o8NsXw8R2REI2NKiKmeVSSdA4HtFx6BdcCGyjDwkn3PSkeZMEVS03rHzYQMG2ecC2zqSXLHfXBc1ic/g1HYpIUO4G7G26o+JgYvNN30choFRW59tvTC/3R5QRQwLViPEaWYtaZOnycAwSA5xoazfXfxnH6ewmt6UiySed7dpcH0C50hW2bqyQAvW3WtN9PXasMRcwxer9dlmX6DYmoPzrgAG+0AhiET0RgssMFjGwJk0nqnfZMuPDf3yNZSGxb5j4+9wUtUw2r53A6igjcrfFJJzIH9B1gkITvsvnEid1wkMfTAOpFUrKjOFcVj04rmYae4onxmG86uaHdoxIzsbDE1KsXVzGQlRV6hF1daGweQSGmZnc+OQjhS7I7GJ4i/PEewbBjUL6ieSo4BXiWWNr9wxjuNRmlBqKvjvFy8jtEITd1UOG8XSogZAgtnrZ0PTRY7BMK8gV2aQPCaOoQMK5cCKw+DURVf7Hi4STKzq6mRoA9zGtcCSC7MoFWsjenABnwm6uXtUnjRXLtqJ6m3cisYcVMWkn/o1xnzUf6fdzFspXXdzqkKMAzMySHpaCuRZ+X5EI+8hiqsYWZztXvnkszaaaGKJbR5CQbOKu+wZLgk4f998x1S62CVpU+MD95pRZSsvI=
    app: ouracademy