language: node_js
node_js: '10'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
install:
  - yarn global add codecov
script:
  - yarn test --coverage
  - codecov
